### ISSUE TITLE
Move ISCSI servers

### ISSUE THREAD

**Issue by hakasapl** [CCI-MOC/ops-issues#1021]
neu-03-30, neu-05-30 ISCSI servers will move to R3-PB even side.

**Comment by naved001** [comment]
The iSCSI servers were moved to R4-PA-C02 and C04. Because we don't have enough 40G ports we connected single nics of these servers, I then moved all the VLANs to a single nic and redid the network configuration on the hosts and on the switchports. These intel servers use javaws for console and to view that on macos I used Openwebstart.

A VM on one of the servers is the BMI iSCSI server which is still not running which I will track in a new issue.
