### ISSUE TITLE
Create language around contents of PI bill to be included with letters to PIs about June/July usage

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#1050]

**Comment by joachimweyl** [comment]
If it helps to see the data [here](https://docs.google.com/spreadsheets/d/1P6BrbyTtOYpo_BRUaQs0wDcI8w6iH-axCPbYqEwiMLM/edit?usp=sharing) is where I am starting to organize the invoice data into different sheets for different PIs.

**Comment by joachimweyl** [comment]
The sheet is fully updated with storage as well as an individual sheet for each PI, it also has PIs that are internal only highlighted in red.
Note: some PIs only have storage listed, this is because storage is based on ColdFront requests, and SUs are based on usage. This means that if a project has no running Pods/VMs but does have a chunk of storage reserved for the project we will count that.
