### ISSUE TITLE
Details needed to connect the A100 system in R8-PA-C23 to the OCP test cluster in R7-PB-C19

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#1059]
As a network engineer (Nick or equivalent) I want to know all the details necessary to connect the A100 system in R8-PA-C23 to the NERC OpenShift Test Cluster in R7-PB-C19.   A patch panel with HU and BU ports exists next to R8-PA-C23.

In order to simplify this task for Nick we want to gather the following information questions in italics:

- What switches are in the two racks
   - No HU switch in R8-PA-C23 
   - _What is the HU switch in R7-PB-C19_
- _Where is the HU patch panel in relation to R8-PA-C23 (@aabaris ?)_
- _Which vlans does the A100 need to be connected to in order to connect to the test cluster?_
- _Any other required network settings eg. stp?_
- _network port types on A100_
-  _OBM networking password for the machine_

Any other details?

**Comment by joachimweyl** [comment]
This is for https://github.com/CCI-MOC/ops-issues/issues/1039

**Comment by aabaris** [comment]
There are patch panels R8-PA-C21 (next to the server rack - R8-PA-C23) It contains patch ports to HU/BU/NEU networks.  We need to confirm with Nick that it is suitable for use to create a network path to the nerc-ocp-test cluster.

There is a table of network/vlan information here:
https://github.com/OCP-on-NERC/docs/blob/main/architecture/network.md
But it might be better if we requested from Nick that he provides same vlan and port configuration as one he applied to an existing osp-test worker node rather than attempting to reconstruct what the configuration should be, and also request that OBM vlan is trunked to that server as well.  (Additional details about OBM network in my last paragraph)

Network ports on the Lenovo server might depend on specific HW build.  This should be looked up via any spec info provided by lenovo specific to the loaner unit or looking at the physical device, or via serial number lookup at https://support.lenovo.com/us/en/parts-lookup   

In addition to the host networking, connectivity for OBM is also needed.  By default these servers use an OBM switch built into the chassis that is shared with all servers in that chassis (so potentially NEUs servers are already routed to NEU OBM network).  I believe there are 2 options:  
1) Work with NEU to see if the entire chassis could be taken over for this purpose, connecting the whole management module (SMM) via 8p8c twisted pair copper cable to the NERC openshift OBM network.  
2) configure server to share OBM interface with the main host interface (and request that Nick ads OBM vlan trunk to the same port), but keeping in mind this option requires additional investigation and we likely encounter caveats.  There's one bug report for us to keep in mind already:
https://datacentersupport.lenovo.com/us/en/products/servers/thinksystem/sd650v2/7d1m/7d1mcto1ww/j700ew90/solutions/ht512278-xcc-shared-nic-mode-does-not-work-after-activating-lacp-on-ocp-ports-on-thinksystem-v2-servers-lenovo-thinksystem-sd630-v2-sd650-v2-and-sd650-n-v2

I hope this provided more information than confusion.  Please let me know if I can further clarify or provide additional info.

- Augustine

**Comment by syockel** [comment]
What NIC is in the node?  Typically these have Mellanox CX6.

**Comment by msdisme** [comment]
@aabaris do you have any details of BU network switch in R8-PA-C23 (or is it an NEU switch?)
        - _Scott suggests perhaps we could route via NESE network?_

**Comment by msdisme** [comment]
Model number is Lenovo SD650N V2 -- I'll ask Doug for OBM passwords and serial number.

**Comment by msdisme** [comment]
Doug said: The folks who loaned it said to do a “factory reset” and then the default password.

I have an email for a person who is savvy at systems that we can ping - not putting it here due to public repo.

**Comment by aabaris** [comment]
> 

Michael,

Yes, I'm the one who configured that BU switch in R8-PA-C23.  It is connected to BU compute cluster's private networks.  There is no suitable path to NESE from that switch.  I haven't been to the datacenter in a while, so I do not know if an NEU switch has been installed in that rack in addition to BU's.

My understanding is that we would need a number of NERC VLANS + NESE VLAN + OBM network available for this server in order to make it part of nerc-ocp-test cluster, is that not so?

Have we heard from Nick Amento about any options to connect this system?

I looked up some more details on the lenovo server (best confirmed based on the serial # that Hakan is pursuing), but it looks promising that there's likely be 1 copper gigabit port and 1 SFP28 port [1].  It looks hopeful that at least we would be able to dedicate the gigabit interface to be used by servers BMC (XCC in leonovo speak), rather than having to go the  through chassis switch (CMM) and dedicate the SFP28 25Gb port to host networking [2].  

Depending on what options Nick suggests we may need to allocate either a 25Gb DAC cable or appropriate optic transceivers if we need to patch using fiber.

[1] https://lenovopress.lenovo.com/lp1396-thinksystem-sd650-n-v2-server#system-architecture
[2] https://pubs.lenovo.com/xcc/NN1ia_c_configuringethernet

A

**Comment by msdisme** [comment]
I think @syockel is discussing this with @amento617 - and I think you are correct about the network state.  I'll reach out to Greg and techsquare to see if we can get eyes on the rack (photo?) and with @naved001  and Hakan (who's on PTO this week) to see if we have switch we could "magic" over there if needed (fingers crossed)

Details from what Augustine outlined that we want to know are:
- serial numbers and model numbers of the Lenovo SD650N V2
- clarity on whether any NEU or other switches (not the BU ones) are already in rack, or is there space for one (water cooled rack, does that need anything special in the way of switches?)
- which NIC is in the node (I also think mellanox- will try to confirm)

**Comment by aabaris** [comment]
I asked one of BU folks at the data center today, to see if the server can be easily identified and if serial number is visible.  I'll update if I have more info from the outcome of this.

If I may suggest, we should focus on:

1) getting the serial number of the A100 host system so we could work with precise configuration specs and hw network port info.  (I'll let you know if we were able to get it, or if we need to engage someone with more info and access)

2) finding out from Nick what our options are for connecting to networks we need.

3) hold off on pursuing NEUs switching/network info, based on my understanding of things, there is no magic and this is very unlikely to get us what we need.

A

**Comment by aabaris** [comment]
Update from the field:

Serial number is: S4CNH653
Matchine type: 7D1N-CT01WW

Based on this sticker:
![IMG_5995](https://github.com/CCI-MOC/ops-issues/assets/8989161/73b5c362-7e9d-44f0-aca7-5084e29cd824)

MAC addresses for the XCC (BMC)
![IMG_5992](https://github.com/CCI-MOC/ops-issues/assets/8989161/68ef1a71-e8d1-4a00-8cf4-0a3cca60922d)

The top half of the rack.   SD650N V2 server is the bottom of the top half, what they call U1-2.
![Image from iOS](https://github.com/CCI-MOC/ops-issues/assets/8989161/6f84f114-154d-4e7a-b49f-0aca8fd03655)

**Comment by aabaris** [comment]
From parts lookup based on the serial number, I am finding:

GPU:
- Nvidia SXM4 400W 40GB HBMe GPU

Network adapters:

- Mellanox DWC ConnectX-6 HDR/200GbE 1-port x16 PCIe 4.0 Adapter 
- Onboard Gigabit and 25 Gb Ethernet ports (part of the System Board, ICE Lake, with TPM, With LOM, SD650 V2, SD650-N V2 )

Based on this and server documentation, connections will be needed:

- 1 Gb Ethernet RJ45 for the XCC/OBM management:
    - Server: onboard eth port 2, for XCC  (making sure we configure bios/xcc to use that adapter as XCCs network interface)
    - Switch: access port for OBM VLAN 2170  - 10.30.0.0/22

- 10/25Gb connection to the main host network interface, SFP28 
    - Server: onboard eth port 1
    - Switch: At least VLANS 2174  (10.30.8.0/24 TEST baremetal network) and 2175 (10.30.12.0/24 TEST storage backend), however as I previously stated, we should consult Nick about what configuration has been applied to ports allocated to current nerc-ocp-test cluster worker nodes and base it on that - I think there's native vlan and trunked vlan and I would only be making guesses of how that should be configured.

Augustine

**Comment by syockel** [comment]
From my Slack with Nick Amento yesterday:
  [1:55 PM]
if it's just one machine, ideally we just run it back to a switch with NERC VLANS

**Comment by msdisme** [comment]
@syockel @amento617 - what else do you need?

**Comment by amento617** [comment]
Hello Augustine, All,

One question I have though is how many of these SD650 blades will
eventually be connected to NESE?

From reading through this and some SD650v2 documentation, it seems the
easiest way to provide this node with NESE networking would be to run a 5M
SFP28 DAC cable from the SD650 system in BU cabinet 8-A-23 to the ZDA
cabinet 8-A-21. This connection should land on the lower Harvard Cisco
93180YC switch which we can provide NESE VLANs to. I can ask Mike next time
he is out in MGHPCC to run this link - We should have the needed cable in
stock. Is cabinet 8-A-23 currently locked?

From the Lenovo documentation it appears the SD650 SFP28 port can share
both data and management functionally via a tagged vlan for the XCC, so a
single connection can facilitate both.

https://lenovopress.lenovo.com/lp1396-thinksystem-sd650-n-v2-server#remote-management
Remote management

Both the 1Gb and 25Gb embedded ports on the front of the SD650-N V2 offer a
connection to the XCC for remote management. This shared-NIC functionality
allows the ports to be used both for operating system networking and for
remote management.

The 1Gb and 25Gb embedded ports support NC-SI. You can enable NC-SI in the
factory using the feature codes listed in the following table. If neither
feature code is selected, both ports will have NC-SI disabled.
Table 34. Enabling NC-SI on the embedded network ports
Feature codeDescription
BEXY ThinkSystem NC-SI enabled on SFP28 Port
BEXZ ThinkSystem NC-SI enabled on RJ45 Port

IPMI via the Ethernet port (IPMI over LAN) is supported and is enabled by
default in the SD650-N V2. For CTO orders you can specify whether you want
to the feature enabled or disabled in the factory, using the feature codes
listed in the following table.
Table 35. IPMI-over-LAN settings
Feature codeDescription
B7XZ Disable IPMI-over-LAN
B7Y0 Enable IPMI-over-LAN (default)
thanks,

-n

**Comment by msdisme** [comment]
@aabaris do you know the locked status of 8-A-23 ?

@amento617 re:"One question I have though is how many of these SD650 blades will eventually be connected to NESE?"  

Some background on this system: It's a loaner for initial testing.  The eventual plan is to have a larger installation of them, probably in a different location, with better up-front planning (sorry about this time.)  (Apologies if I misunderstood the question.)

**Comment by aabaris** [comment]
8-A-23 is not locked.

**Comment by amento617** [comment]
Hello Augustine, All,

Mike Ethier helped me run a DAC cable to cabinet 8-A-23, however we
couldn't determine exactly which server to connect it to. It should be
ready to go if someone can connect this SFP28 cable to the needed system.

What will the hostname of this system be so I can label the switchport
appropriately?

For the XCC/OBM interface, this will be tagged lan 2170.

The switchport is currently configured for VLAN 2174 NATIVE (not tagged)
and VLANs 2175 & 2170 tagged.

interface Ethernet1/22
  description RC:NERC:A100 test blade 1 - cabinet 8-A-23 NERC
  switchport
  switchport mode trunk
  switchport trunk native vlan 2174
  switchport trunk allowed vlan 2170,2174-2175
  spanning-tree port type edge trunk
  no shutdown

thanks,

-n

**Comment by msdisme** [comment]
How about: a100test1-8a23

**Comment by msdisme** [comment]
@hakasapl can you connect that cable?

**Comment by hakasapl** [comment]
I've connected the SFP28 in the rack

![Image](https://github.com/CCI-MOC/ops-issues/assets/40907639/f1e72fe6-e4ba-407f-b07b-01d3dfc284b8)

**Comment by hakasapl** [comment]
Is the ipmi tag on the 25G port on the node configured already? If not, do we know the vlan id so I can configure the tag on the server side?

@amento617 @aabaris ?

**Comment by amento617** [comment]
Hello,

On the network side this is tagged as VLAN 2170.


-n

**Comment by hakasapl** [comment]
OBM was factory reset and is now setup with the following, using the shared DAC cable:

```
IP: 10.30.0.124
Netmask: 255.255.240.0
Gateway: 10.30.0.1
VLAN: 2170
```

@jtriley confirms it is reachable.

**Comment by joachimweyl** [comment]
Reachable and testing started.
