### ISSUE TITLE
Allocation of VMs for ROSE course

### ISSUE THREAD

**Issue by reihl** [CCI-MOC/ops-issues#1307]
Hi,
I would like your help with the allocation of 25 OpenShift based VMs.
The VMs are needed for a course taking place next week. It is a course similar to the previous ROSE course, where a similar allocation was done several months ago.
I'm attaching a link for a discussion regarding the previous ROSE allocation:
(450)[https://github.com/CCI-MOC/ops-issues/issues/450]
This request is same to (620)[https://github.com/CCI-MOC/ops-issues/issues/620] apparently the server from the last week was deleted yesterday.
Thanks in advance,
Rei

**Comment by msdisme** [comment]
Our data center is currently down due to the scheduled annual power shutdown at the Massachusetts Green High Performance Computing Center (MGHPCC) in Holyoke. This shutdown is from May 22, 2023, at 8:00 AM ET to May 28, 2023, at 8:00 PM ET.   

The Mass Open Cloud has also been replaced by the New England Research Cloud (NERC). I am sorry for the difficulty this may cause the work you are doing on ROSE. This means we will need to work with a different set of systems to continue supporting the ROSE project, and this may take a bit of effort today, tomorrow, and next week. 

Could you please explain a detail you mentioned in the ticket? 
"Apparently, the server from last week was deleted yesterday."

**Comment by sleviim** [comment]
Hi @msdisme ,
Thanks for your reply.
As moving to NERC, do you think we shall have our environment ready by the beginning of the course?
Is there something else needed from our side?
If it's possible, and to make things easier, we wish the "new env" to be the same as the "old env" we had last year,
although the platform was changed.

I believe that by saying 
> "Apparently, the server from last week was deleted yesterday."
@reihl meant the project was closed and no longer accessible:
https://github.com/CCI-MOC/moc-openshift-projects/pull/35

**Comment by msdisme** [comment]
Let us know the timing please.

**Comment by sleviim** [comment]
Course critical dates are July 21st-25th.
We'd like to have the VMs before, so students would be able to explore it a bit.
If VMs will be available ~ July 14th it will be awsome!
WDYT?

**Comment by sleviim** [comment]
Kindly reminder @msdisme

**Comment by reihl** [comment]
@joachimweyl Thank you! Do you think you can fulfill this request?

**Comment by joachimweyl** [comment]
Hello @reihl,
This is something you can setup yourself now that the NERC exists. It will be 25 VM's in OpenStack instead of OpenShift as NERC does not have OpenShift virtualization.
Please follow the instructions [here](https://nerc-project.github.io/nerc-docs/get-started/user-onboarding-on-NERC/) to create your NERC PI account and the once that is created you can spin up whatever VM's you need.

**Comment by msdisme** [comment]
@reihl - just checking in to make sure that you are set

**Comment by reihl** [comment]
Tried to register to NERC and opened "Support Ticket Opened [#003325]" Now wait for response

**Comment by hpdempsey** [comment]
Hi Rel.   I don't believe ROSE has a budget to cover MOC expenses currently.   I can approve the resources for the course today, but I need to know how your group will pay for them, because this was not included in our research budget.   MOC charges are here:  https://nerc-project.github.io/nerc-docs/get-started/cost-billing/how-pricing-works/

**Comment by msdisme** [comment]
Team set up, need to follow up with details on how they may pay in the future.  Closing and tracking that with Nancy in a different workstream (not github)
