### ISSUE TITLE
Notify ESI and MAAS users of possible disruptions on July 15th, 2024 due to changes to CSAIL network. 

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#1340]
- [ ] Notification of ESI slack channels and possibly affected partners (I do not think we are using ESI for bare metal nodes at the current time.
- [ ] #1341

**Comment by naved001** [comment]
Impact on MaaS users:

* The research ceph nodes were provisioned using MaaS but all on an internal network (10.128.0.0/19). I had a ssh jump box on this network that I have now migrated to the NEU public network at 129.10.5.155 (`rceph-bastion.massopen.cloud` now points to the new address). So, the ceph team will continue to have access to the research ceph cluster without interruption. (@knikolla)

* The research ceph hosts will lose access to the internet that is because the network 10.128.0.0/19 routes to the internet via the csail public network that MaaS uses. This will need to be resolved. Simplest solution is to make the jumpbox the gateway for this network. Not sure how urgent this is (@hakasapl)

* oct-4-7 is assigned to Emmanuel according to MaaS. The machine is up at 128.31.28.126, not sure if he's still using it.

**Comment by msdisme** [comment]
@cecchet - see above,  are you using OCT-4-7?

@hakasapl do you know if the "intel nodes" are using CSAIL addresses?   Also, what is the level of complexity to setting up a jumpbox for the research ceph hosts?  @knikolla do you know, or is that an Amin query?

**Comment by naved001** [comment]
> do you know if the "intel nodes" are using CSAIL addresses?

they are not on csail addresses. they are not on my public network actually.

> Also, what is the level of complexity to setting up a jumpbox for the research ceph hosts?

the jumpbox already exists and access to the research ceph nodes will not be interrupted. Though, access to internet from the research ceph host will be cut off once the csail network goes down.

**Comment by hakasapl** [comment]
rehlai nodes are unaffected (they are on the NEU network)

**Comment by msdisme** [comment]
changed status message to be priority 1 for a system affected.

**Comment by naved001** [comment]
> see above, are you using OCT-4-7?

The answer is yes, and now that node has been moved to the neu network at 129.10.5.154 (oct4-7.massopen.cloud)

**Comment by naved001** [comment]
> Though, access to internet from the research ceph host will be cut off once the csail network goes down.

This has also been taken care of, the host `rceph-bastion` now routes to the internet for research ceph hosts.
