### ISSUE TITLE
Document ESI workflow with people and handoff, time, throughput

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#1373]
Turned out a system had some issues which caused a chain reaction.

ESI workflow with people and handoff, time, throughput

**Comment by hakasapl** [comment]
In the interim period there will be a lot of instances where we want to move a node from outside of ESI to inside of ESI. This requires the following steps:

* Current owner of the node needs to cleanly remove the node from their cluster and give @hakasapl access to its BMC.
* The node needs to be in a rack with an ESI-managed switch.
* @hakasapl will set the BMC user account, the switchports, and the networking for the BMC.
* @hakasapl will create manifests and submit a PR to [esi-pilot](https://github.com/CCI-MOC/esi-pilot)
* @tzumainn will review the PR by testing inspection and deployment
* @tzumainn will make the node available in ESI if everything passes

Because this involves three separate persons, everyone needs to know the priority of a given request to do this and any deadlines associated with it. Usually this can happen within a day if there are no issues.

@tzumainn let me know if you wanted to add anything

**Comment by tzumainn** [comment]
This looks accurate! The only thing I'd add is that the inspection + deployment testing usually takes 1-2 hours.
