### ISSUE TITLE
Install the 2 AMD GPU cards and make available under ESI. 

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#1426]
The 2 AMD GPU cards should be at the NERC attention @hakasapl .  

Please arrange for them to be installed - techsquare? And available under ESI.

Price to charge to be addressed in https://github.com/CCI-MOC/ops-issues/issues/1427

**Comment by msdisme** [comment]
@hakasapl ok for this sprint?

**Comment by hakasapl** [comment]
@msdisme didn't we say we would hold off on this until after the network maintenance in the winter session? The reason is that the switch in this rack is still Harvard controlled so we can't do anything ESI related here until after that maintenance.

**Comment by msdisme** [comment]
@hpdempsey that puts us into January, is that going to be soon enough for the researchers?   @hakasapl if memory serves you wanted to combine these with other GPUs.  Since these are loaners, we were planning in #1427 to only charge for CPU cycles so we should make sure we think that through.

**Comment by msdisme** [comment]
From Slack: @HeidiPD:do the RH members looking for the AMD GPUs want them BM or in OpenShift/Stack?
Heidipd: I think Bare Metal

**Comment by msdisme** [comment]
@hakasapl do we have some systems we can put the AMDs in short term - at the is point it would even be ok to put them into some OCT under ESI systems that we are not charging for.

**Comment by hakasapl** [comment]
I wouldn't want to put it in the very old dell hardware in OCT4. I will check out our stock tomorrow when I'm on-site

**Comment by hakasapl** [comment]
@msdisme to follow up on what you said about combining AMD + nvidia in one node and how that complicates billing. I think we should instead double up the nvidia GPUs on the R740s (so 16 nodes of 1xv100 becomes 8x nodes of 2xv100). Then the 8 now empty nodes can accommodate other new hardware. Of course that requires a full downtime for these nodes

**Comment by hpdempsey** [comment]
I got back to the team that wants to use the M210s and they have started an OpenStack project to do that.  I thought from our previous discussion that Hakan thought that would be easier than adding them through ESI bare metal.  They want to use them ASAP, and have already started using the OpenStack project (called Triton getting ready for the GPU.   They would also like to have an A100 in that OpenStack project.

**Comment by msdisme** [comment]
@hpdempsey, are they in production OpenStack or in a standalone OpenStack cluster?   Do they need them in separate systems or can we put both cards in one and that will work for them.

**Comment by hakasapl** [comment]
We do not currently have a node to put these in unless we can down ideally 2x R740xds from prod

**Comment by hakasapl** [comment]
Notes from discussion:

The only short-term option is to down 2x R740xds from either Openshift or Openstack and reconfigure them so that one has 2xV100 and the other 2x AMD GPU (instead of 1x V100 each). They would then have to be re-added to NERC in this new config (potentially needing a new flavor since configuration changed?)

**Comment by msdisme** [comment]
@jtriley @StHeck @aabaris please see [comment here](https://github.com/CCI-MOC/ops-issues/issues/1426#issuecomment-2521280231) . Looking for guidance on whether this would be possible next week. Obviously details to figure out, but wanted to get initial feedback.

**Comment by msdisme** [comment]
@larsks you mentioned a way to move nodes in and out of a TripleO deployment. Could you put the details here please?

**Comment by larsks** [comment]
@msdisme what I said was that it is possible to remove a node from OpenStack without having to re-run the installer.

You can [disable the compute service](https://docs.openstack.org/nova/xena/admin/services.html) on a node such that nothing will get scheduled on it, at which point you can pull the node without otherwise impacting the cluster. However, this will leave you with work to do next time you want to run the installer (e.g., for an upgrade, or to change configuration options), since a missing node ~~will~~ may cause the deployment process to fail (I'm being a little ambivalent there because my experience with the installer is now several years out of date).

**Comment by msdisme** [comment]
@jtriley I think the path would be to take 2 740 systems with v100's off openshift.  Move the 2 V100's to one 740, put the two AMD's into the other 740.  Kim points out this affects the SU.  Flip side is it gives us greater density.

**Comment by joachimweyl** [comment]
@jtriley strongly advises against adding the 740 back into OpenShift because of the SU issue. If we really need to get AMD GPUs running we could take 1 740 out of OpenShift and put the two AMD chips in and save the V100 for later, this would mean we are 1 V100 down in OpenShift. @hakasapl do we have any other hardware we could put the AMD GPU's into?

**Comment by msdisme** [comment]
That is a good point.  @hakasapl @joachimweyl can we please get @hpdempsey an eta on the change?  We'll revisit the rest of the v100's later on but the team working on the AMDs is hoping to finish up before the holiday break (12/23)

**Comment by hakasapl** [comment]
We do not have any other hardware for this. It would have to be one of the R740s. I believe the NERC team is busy this week so earliest we could do is next week.

**Comment by hakasapl** [comment]
The node is available in ESI now
