### ISSUE TITLE
HW requirements for NESE connection within UMAss Row 6 racks

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#223]
Placeholder for @hakasapl to add details on the hw required to connect to NESE.  MCO nw details currently here: https://github.com/CCI-MOC/ops-issues/issues/156  Details on MOC/OCT?Operate First nw connections here in attached graphic.
<img width="933" alt="Screen Shot 2021-04-02 at 4 54 49 PM" src="https://user-images.githubusercontent.com/6126065/113453544-3961e980-93d4-11eb-944b-b587fd86db14.png">

**Comment by hakasapl** [comment]
Whoops I forgot to add my info to this. For the UMass NESE gateway we're using a fairly beefy single server to act as the gateway - the node needs to be capable of not only serving storage to anyone outside of systems you control, but also be responsible for the routing between the client and NESE.

Our specs are:
Intel(R) Xeon(R) Gold 6126 (24 cores - somewhere in that ballpark should work)
192 GB RAM (Higher ram the better for a storage server because the system will read cache)
Our node has about 60TB of HDD storage, so we can use it as a data buffer system if need be one day (not important, we just happened to have this server left over)
2x512 GB SSD in RAID 1
We currently only have a 10G NIC in that node (working on an upgrade) - I would highly recommend going with a 100G nic with two ports (one to the NESE connection, the other to MOC networks or wherever you want to serve storage).

I think a system of similar caliber is a good start. After that gets deployed we can talk again about redundant gateways, but that's a whole other problem to solve with the way NESE works.

**Comment by msdisme** [comment]
Dun Dun
