### ISSUE TITLE
Create NFS volumes for Power 9 openshift

### ISSUE THREAD

**Issue by larsks** [CCI-MOC/ops-issues#250]
Create 30 volumes for power 9 nfs pvs. NFS0000-NFS0029, 10GB each.

**Comment by larsks** [comment]
The NFS server is now exporting the following NFS filesystems:

```
/mnt/pool0/vols/power9/NFS0000
/mnt/pool0/vols/power9/NFS0001
/mnt/pool0/vols/power9/NFS0003
/mnt/pool0/vols/power9/NFS0004
/mnt/pool0/vols/power9/NFS0005
/mnt/pool0/vols/power9/NFS0006
/mnt/pool0/vols/power9/NFS0007
/mnt/pool0/vols/power9/NFS0009
/mnt/pool0/vols/power9/NFS0012
/mnt/pool0/vols/power9/NFS0013
/mnt/pool0/vols/power9/NFS0014
/mnt/pool0/vols/power9/NFS0015
/mnt/pool0/vols/power9/NFS0017
/mnt/pool0/vols/power9/NFS0018
/mnt/pool0/vols/power9/NFS0019
/mnt/pool0/vols/power9/NFS0021
/mnt/pool0/vols/power9/NFS0022
/mnt/pool0/vols/power9/NFS0024
/mnt/pool0/vols/power9/NFS0027
/mnt/pool0/vols/power9/NFS0002
/mnt/pool0/vols/power9/NFS0008
/mnt/pool0/vols/power9/NFS0010
/mnt/pool0/vols/power9/NFS0011
/mnt/pool0/vols/power9/NFS0016
/mnt/pool0/vols/power9/NFS0020
/mnt/pool0/vols/power9/NFS0023
/mnt/pool0/vols/power9/NFS0025
/mnt/pool0/vols/power9/NFS0026
/mnt/pool0/vols/power9/NFS0028
/mnt/pool0/vols/power9/NFS0029
```

We now need to arrange to expose the power9 cluster to the appropriate storage network. @naved001 should we add VLAN 210 to the power9 systems, or is there an existing VLAN in the power9 environment we should add to the NFS server?

**Comment by naved001** [comment]
I think we should add VLAN 210 to the power9 systems, but there's some weird networking configuration that I'd like to fix first.

There are 2 Ethernet interfaces one each power9 server. 

Interface 1 is connected to our foreman vlan 201 (native), and CSAIL public network VLAN 3803 (taggeD). This is all good.

Interface 2 has default interface configuration and I think has all VLANs are allowed. However, that does not mean it has access to all our VLANs since the two ethernet switches connect to an intermediary brocade switch which connects to our kaizen switches. The intermediate brocade switch only has those VLANs created that we want to actually trunk (so even though the interswtich trunk port has all VLANs enabled they won't actually go through).  But VLAN 1 is created by default and most switches don't like that being disabled, so I think I would have to put Interface 2 on some non default native VLAN and then add VLAN 210 as tagged on it.

**Comment by larsks** [comment]
>  so I think I would have to put Interface 2 on some non default native VLAN and then add VLAN 210 as tagged on it.

That seems fine. Any reason we can't just make VLAN 210 the native VLAN?

**Comment by naved001** [comment]
Interface 2 is on default VLAN 1 and there's a network (192.168.96.0/19) on it, but I *think* it's not used for anything.

**Comment by naved001** [comment]
https://docs.massopen.cloud/en/latest/clusters/kaizen2/Kaizen-2.html#lenovo-ceph-for-ibm-power9-vlan-210-and-211

That document says that at some point there was some lenovo ceph on that network that the IBM's were using? @rob-baron do you if 192.168.96.0/19 still used for anything?

**Comment by naved001** [comment]
Rob's response:
> I have no idea.
9:23
Ceph is not a good solution for 3.11 as everyone has access to everyone’s data.
9:24
That said, to use the GPUs, everyone can gain access to everyone’s project (so I just give it to them) - ie, you need to read and write to the local volume, which means you have access to the all of the openshift config files there.

**Comment by naved001** [comment]
I configured the p9 nodes to be on the NFS VLAN. They got an IP using DHCP. @rob-baron you should be able to mount those volumes now.

**Comment by larsks** [comment]
@rob-baron the NFS server address is 10.253.0.10. Full paths are as noted [earlier](https://github.com/CCI-MOC/ops-issues/issues/250#issuecomment-838704594).

**Comment by rob-baron** [comment]
Here is the yaml that I created the PV with:

**Comment by larsks** [comment]
@rob-baron I think you forgot to include the YAML in that last comment.
