### ISSUE TITLE
NESE Space

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#271]
As a user of Operate First Projects I want to have enough space to store data so that I may evaluate it and, in some cases, safe it off to tape. 

- [x] Quote for ordering space on NESE
- [x] Review if 202TB is enough storage
- [ ] if it is order the cluster
In the meantime how much space needed
- [ ] confirm short term needs - propose 20TB till new cluster in place and clear that amount with Wayne.

**Comment by larsks** [comment]
> As a user of Operate First Projects I want to have enough space to store data so that I may evaluate it and, in some cases, safe it off to tape.

I'm not sure about this phrasing. I think very few users want to "move data to tape". I think more accurately this is "As a user of Operate First Projects I want to have enough space to store data so that I may evaluate it. When I am no longer actively using data, I want a way to archive it without consuming my available space allotment, while still permitting access to it in the future."

And I wonder if this intersects with e.g. #260?
