### ISSUE TITLE
Adjust logging on ceph nodes to prevent noise on email alert lists

### ISSUE THREAD

**Issue by larsks** [CCI-MOC/ops-issues#282]
Ceph nodes send email on every root login, which seems excessive.

**Comment by naved001** [comment]
The ceph nodes will no longer send emails on root login and logout. `.bash_profile` and `.bash_logout` were used to send out these emails.

There's a crontab job that sends out alerts every 5 minutes if there's a ceph warning or error. I have now changed it to once a day. We have persistent ceph warning due to our old openstack clients so I think once a day is manageable.
