### ISSUE TITLE
connect Mailman to a CI/CD workflow

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#30]
using MOC IL team initially, 1. Teach, 2. msd to document the how, 3. dependng on complexity teach to Jen?

**Comment by larsks** [comment]
I'm not sure this task makes sense as written.

The [moc-ansible-mailman][https://github.com/CCI-MOC/moc-ansible-mailman/] repository is meant to be part of an automation workflow, that would look something like:

- We have a configuration repository for Mailman
- You make a pull request against the configuration repository to define a new mailing list
- The CI/CD process validates the configuration and uses the modules in moc-ansible-mailman to realize the new mailman configuration

So, the task would be "connect Mailman to a CI/CD workflow", and then teach people how to use that.

**Comment by larsks** [comment]
We have had some discussions about the sensitivity of email addresses. In order to create a new mailing list, there are effectively two required pieces of information:

1. The list name
2. The list owner

If we want to enable people to submit pull requests against a repository in a useful fashion, that would effectively require that we expose owner email addresses. How do we feel about this?

If we *don't* want to expose these email addresses, we can still have a gitops-style workflow, but making changes to the configuration will be an "admin-only" operation (where "admin" means "someone on the moc operation team with access to appropriate credentials").

**Comment by larsks** [comment]
I'm going to close this issue, since we're looking more seriously at simply hosting mailing list operations somewhere else.
