### ISSUE TITLE
Migrate users from k-openshift (3.X) cluster to OCP 4.X (once that's deployed).

### ISSUE THREAD

**Issue by naved001** [CCI-MOC/ops-issues#37]
- [ ] Evaluate how many users/projects can the new cluster support based on monitoring.
- [ ] Identify pilot projects to migrate
- [ ] Communicate and then migrate those pilots.

~Currently blocked on: https://github.com/CCI-MOC/ops-issues/issues/36~

**Comment by joachimweyl** [comment]
@naved001 do we have a migration method to move users from OpenShift 3.x to OpenShift 4.x?

**Comment by naved001** [comment]
I don't think we ever came up with a process at all.

**Comment by joachimweyl** [comment]
Luckily it seems like we no longer have any 3.x users still accessing OpenShift 3.x. Just in case does the base image we are using for OpenShift 3.x & 4.x have rsync? I ask because the [backup and restore feature through rsync](https://docs.openshift.com/dedicated/3/admin_guide/assembly_backing-up-restoring-project-application.html) looks like an option for users to at least backup their applications.

**Comment by naved001** [comment]
I don't know that either as I have barely interacted with the 3.x cluster. I would ask @rob-baron about this as he has a better understanding of the 3.x cluster, the users, and the workloads that ran on it.
