### ISSUE TITLE
Early access to OCP 4 cluster for Jonathan Appavoo

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#373]
As a professor I'd like to be able to access the MOC cluster a bit before the general availability on the 20th so that I may set up things for my course. 

As an MOC operations person I would like to provide that access in a way that is consistent with the approach we are taking for all the students on the 20th so that I am not creating extra work. 

Slack Exchange:  
``` Hi Michael.  Thanks for all the info and help.  Is there any way for me to poke around what is there?
2:52 PM
I just want to get an idea of how things work and what I will be able to run
11:01 AM
Jonathan Appavoo @okrieg @msd  Do you need anything from me to setup an account for me to poke around the
system?  As to my students… not a problem with respect the delaying until you have an on boarding process.
:+1:
2:50 PM
msd:spiral_calendar_pad: I checked in with the team they’re still working on how to actually create accounts
we should be able to get you early access but I don’t have an ETA yet
```

**Comment by jappavoo** [comment]
Thanks so much.  My GitHub id is jappavoo

**Comment by larsks** [comment]
This depends on https://github.com/CCI-MOC/moc-apps/pull/41

**Comment by larsks** [comment]
@jappavoo take a look at https://github.com/CCI-MOC/moc-openshift-projects, which is our interim solution for letting you (and other folks) add projects and users to the openshift cluster. The model is you fork that repository, makes changes as described in the README, and then submit a pull request. Once the PR is approved, the changes should go live on the cluster in a couple of minutes.

Let's use this issue if you have any questions about how things work.

The cluster URL is https://console-openshift-console.apps.ocp-prod.massopen.cloud/; you should be able to log in now, but you won't be able to do anything until you create a project (and include yourself as a user).

**Comment by jappavoo** [comment]
Thanks so much I will try things out tomorrow.

                                            Jonathan
                                                  Appavoo

**Comment by larsks** [comment]
@jappavoo just checking to see if you've had the chance to look at this yet? We would really like to know if it meets your needs while there's still time left in the week to make any necessary changes.

**Comment by jappavoo** [comment]
So sorry the day got away on me.   I will try to get you some feed back tomorrow.

**Comment by jappavoo** [comment]
Created my PR

**Comment by jappavoo** [comment]
At this point my goal was trying to  blindly followed these instructions 

https://github.com/jupyter-on-openshift/jupyterhub-quickstart

to see if I could get a min jupyterhub service running and was then going to customize with my particular containers.    

However my first attempted failed and I need to cleanup after myself and then try again ... I think for some reason my database instance is not coming up... not sure if this is because I need to customize my persistent storage config or there is some other issue.

**Comment by larsks** [comment]
> not sure if this is because I need to customize my persistent storage config or there is some other issue.

Ah, well, this may be related to the fact that we're still working on getting persistent storage configured. That should be ready by Monday.

**Comment by jappavoo** [comment]
Good to know!   Thanks.   Will focus on other aspects over the weekend

**Comment by larsks** [comment]
@jappavoo due to a terrible case of the Fridays I gave you bad information; I was thinking of the operate first cluster when I left the last comment. There are in fact no problems with storage on the MOC production cluster. If you're running into general problems I'm happy to take a look; if you're running into issues that require deeper knowledge of something like Jupyterhub then we'll probably need to find someone else with more experience.

**Comment by jappavoo** [comment]
Thanks for letting me know.  With any luck I will try and look at this again tomorrow then and see if I can figure out what is happening.
