### ISSUE TITLE
Draft notice to OCP 3.11 users  EOL

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#420]
See comments for more details.

**Comment by naved001** [comment]
Hello Mass Open Cloud Users,

The MOC will be upgrading to OpenShift Container Platform 4.9 on baremetal. Our older OpenShift 3.11 cluster will be decommissioned before the end of this year. If you are interested in continuing to use OpenShift on MOC and would like your projects to be migrated then please fill out this [survey](https://example.com). 

For further clarifications and inquiries please open a ticket at https://osticket.massopen.cloud

Thanks,
MOC Staff

**Comment by msdisme** [comment]
Some minor mods:

The MOC will be upgrading the Intel k-openshift cluster  from version OpenShift 3.11 to OpenShift Container Platform version 4.9.   OpenShift 4.9 will be running on bare metal cluster _benefits/differences from an end user perspective?_ 

Our OpenShift 3.11 cluster will be decommissioned before the end of this year. If you are interested in continuing to use OpenShift on MOC and would like your projects to be migrated then please fill out this survey.

While we expect the process for migrating your containers to be relatively straightforward more details on the differences between the OpenShift versions may be found at this [Differences between OpenShift Container Platforms 3 and 4](https://docs.openshift.com/container-platform/4.9/migrating_from_ocp_3_to_4/planning-migration-3-4.html).

_Do we expect people to use, or need to use, the https://docs.openshift.com/container-platform/4.9/migrating_from_ocp_3_to_4/about-mtc-3-4.html?  Any other details on what their experience should be like - my sense from discussions with  @rob-baron is that most users will just need to redeploy?_

**Comment by larsks** [comment]
> OpenShift 4.9 will be running on bare metal cluster benefits/differences from an end user perspective?

I think the benefits and differences are primarily in the move from 3.11 to 4.9, rather than in the move from OpenStack to bare metal.

> While we expect the process for migrating your containers to be relatively straightforward more details on the differences between the OpenShift versions may be found at this Differences between OpenShift Container Platforms 3 and 4.

I don't think that's a useful end user reference. Most (all?) of the differences in that document are primarily of interest to people *deploying* openshift, e.g.:

- Different installation tools
- Use of RHCOS vs RHEL
- Operators
- Use of CSI drivers for storage
- Etc.

It doesn't really address any differences at the container level and won't help people transitioning their workloads from 3.11 to 4.9. I'm not sure I would refer people to that document as part of our announcement; I worry it would just sew confusion.

> my sense from discussions with @rob-baron is that most users will
> just need to redeploy?

I think that will be the easiest method by far, and for people who do
run into some sort of problem, we can probably help them on a
case-by-case basis.

**Comment by rob-baron** [comment]
Another benefit from running on bare metal as opposed to our OpenStack deployment is that it will be higher performance due to the etcd not becoming overwhelmed and constantly having a leader reelection.

**Comment by naved001** [comment]
Few questions:

1. What do we do when people fill out the form? What are we going to do with it?
2. Will we help people with the migration and/or moving any large PVs?

> It doesn't really address any differences at the container level and won't help people transitioning their workloads from 3.11 to 4.9. I'm not sure I would refer people to that document as part of our announcement; I worry it would just sew confusion.

I agree, we should keep this announcement simple. 

> we can probably help them on a
case-by-case basis.

That's what I think too and they can open a ticket for that.

In my original note, I would get rid of the part that says "projects to be migrated" because I think it sounds like we'll somehow migrate their workloads in the background.

> Hello Mass Open Cloud Users,
> 
> The MOC will be upgrading to OpenShift Container Platform 4.9 on baremetal. Our older OpenShift 3.11 cluster will be decommissioned before the end of this year. If you are interested in continuing to use OpenShift on MOC please fill out this form [here](form.example.com). Once your project is created on the new OpenShift cluster you can start deploying your workloads.
> 
> For further clarifications and inquiries please open a ticket at https://osticket.massopen.cloud
> 
> Thanks,
> MOC Staff

**Comment by naved001** [comment]
I think we are going to wait to send out this email until we have:

1. more capacity on the `ocp-prod` cluster.
2. have a proper onboarding system in place. 

Once we have those, we can send out an email pointing user to the onboarding system's signup page.

**Comment by naved001** [comment]
Just some of my thoughts:

Resources currently allocated by the K-Openshift openstack project (that hosts the ocp3 cluster) are:

vCPU: 298 allocated out of 434.
RAM: 1 TB out of 11TB
~10TB of Storage.

If a node has 40vCPUs and 128Gigs of memory. then we would need 8 such nodes to be added.

**Comment by larsks** [comment]
We have available nodes already and we're just waiting on networking equipment; is that correct?

**Comment by rob-baron** [comment]
Keep in mind that we have several older projects on k-openshift that we should have cleaned up and that we needed to scale up the cluster towards the end of the semester.  After the semester was over, we scaled things back a bit  as fewer people were using it.

**Comment by joachimweyl** [comment]
this is replaced by #816
