### ISSUE TITLE
Setup OCP staging environment

### ISSUE THREAD

**Issue by naved001** [CCI-MOC/ops-issues#441]
Ideally with 3 controllers and at least 2 workers. 

From the top of my head, things we'll need to do regardless of what hardware we put this on:
- [X] Reserve IPs and VLANs -
- [X] Create ceph pool for OCS and the aws secret with cluster details
- [X] DNS configuration
- [x] SSO create client/secret and corresponding aws secret
- [ ] other secrets

Hardware specific tasks:
- [ ] Configure networks on nodes
- [ ] disk configuration
- [ ] boot order

**Comment by naved001** [comment]
Since I had 3 nodes available, I did end up deploying it. 

https://console-openshift-console.apps.ocp-staging.massopen.cloud/dashboards 

it's currently on neu-5-13, bu-23-105, bu-23-111. not all of these nodes have SSDs though so not sure if we'll run into etcd performance issues.

I'll put the login in bitwarden.

**Comment by larsks** [comment]
I think we're really going to want more than three nodes to that we have separate controllers and workers; this will more accurately reproduce the production cluster. I worry that with only three nodes (a) we will run into resource problems and (b) we will see configuration differences between the two environments because in a three-node cluster, all nodes share both `worker` and `master` roles.

**Comment by naved001** [comment]
we now have a functioning staging cluster with 3 controllers and 2 compute nodes. 

I am going to open separate tickets to track networking configuration and OCS installation.
