### ISSUE TITLE
What caused the network outage on Friday?

### ISSUE THREAD

**Issue by larsks** [CCI-MOC/ops-issues#464]
The smaug cluster (rack OCT-3) lost network connectivity for at least an hour on Friday. @hakasapl suggested there may have been some maintenance going on in the data center that caused the outage. Can we get details on that Including which devices and ownership of those devices - this will help identify who to engage?

**Comment by hakasapl** [comment]
There is not a clear reason for the network outage last Friday.

The switch that went down which caused the outage is a Dell Z9100-ON switch (OCT-HUB-3), which is used as the core distribution switch for OCT in row 1 of MGHPCC (which includes OCT[1-4] racks). This switch is owned by UMass as part of the OCT project and operated by me. This switch completely lost power and was unreachable for about 30 minutes. It then came back on its own. Logs yielded nothing useful on the switch.

We recently added the fabric project to that cabinet (same as the switch), and they have access to the PDUs in that cabinet. My assumption is that the power to the switch was accidentally switched off. They said they only messed with their own hardware's power, but it would be the only thing that makes sense in my mind.

Anyway, the switch has not lost power since, and they now know the ports which the switch is receiving power from for the future.

I want to add a second 9100 stacked to the current switch to add redundancy in that rack. I'm working on budgeting for that stuff near-term.
