### ISSUE TITLE
Test and Document steps to migrate MOC project to Swift on NERC

### ISSUE THREAD

**Issue by joachimweyl** [CCI-MOC/ops-issues#511]
- [x] review [nova to swift backup](https://blog.oddbit.com/post/2015-09-29-migrating-cinder-volumes-betwe/) (keep in mind we will use swift not nfs)
> highly likely this will require `backup_driver = cinder.backup.drivers.swift.SwiftBackupDriver` instead of `backup_driver=cinder.backup.drivers.nfs` need to confirm in testing
> we will want to detach instead of using `--force`
- [x] Help @larsks create a NERC Project
- [x] Enable cinder-backup service on MOC
- [x] Enable cinder-backup service on NERC
- [x] @larsks handoff steps to @joachimweyl for user testing
- [x] test migrating sample project from MOC to NERC using UUIDs gathered from https://github.com/CCI-MOC/ops-issues/issues/509 and https://github.com/CCI-MOC/ops-issues/issues/510 utilizing Swift storage on NERC
- [x] [PR](https://github.com/nerc-project/nerc-docs/pull/55)
The conversion piece of this will be managed by #539

**Comment by joachimweyl** [comment]
@larsks
I have a few questions about Migrating from MOC to NERC when you have a moment:
based on your [article](https://blog.oddbit.com/post/2015-09-29-migrating-cinder-volumes-betwe/).
1. Do you know of a way to migrate Snapshots as you did for Volumes?
2. Will the Image selected for the Instance cause problems since the Images are not the same between MOC and NERC?
3. When Importing the backup on NERC how does the `backup-import` know where to find the backup?
> a. Is it reaching out across the network to Kaizen via the base64 `host` and `id` values?
> b. if so how does it let Kaizen know it is allowed to gather that data? Do you have to provide a user/password when requesting the import?
4. How do you know the owner of a Volume? What does that affect?
5. At the end of the article the Volume is not yet associated with an Instance right?
> a. I would need to use `nova volume-attach \ instanceid \ volumeid` or openstack server add volume `instanceid \ volumeid --device /dev/vdb`
6. When you say you need to be an admin to `backup-export` do you mean a project admin or something higher?
7. Is there a way to batch migrate the Security Groups?

**Comment by larsks** [comment]
> Do you know of a way to migrate Snapshots as you did for Volumes?

I don't think that's possible (other than by converting the snapshot into a volume and migrating that).

> Will the Image selected for the Instance cause problems since the Images are not the same between MOC and NERC?

If an instance is configured to boot from a volume, then the image is only relevant when initially populating the volume -- once the system is up, the image is no longer relevant. If the volume is migrated to the new environment, they will be able to boot from it without a problem.

If an instance is configured to boot from an image, most of this discussion is irrelevant. You would need to download your image from one environment and upload it to the new one to boot your instance there.

> When Importing the backup on NERC how does the backup-import know where to find the backup?

I will need to actually step through the migration process myself to answer this (and related) questions. It's been too long since I actually used these procedures. That means I need access to the NERC openstack environment, which I don't currently have.

> How do you know the owner of a Volume? What does that affect?

The *project* that owns a volume controls who can access the volume. The *user* associated with a volume I think is mostly irrelevant.

You can see both the user and project associated with a volume by running `openstack volume show <volume id>`. The project can be found in the `os-vol-tenant-attr:tenant_id` field, and the user is in the `user_id` field.

> At the end of the article the Volume is not yet associated with an Instance right?

That's correct. You would use `openstack server add volume` if you already had a running instance, but if the volume was a boot volume you would use `openstack server create ...` with appropriate options.

> When you say you need to be an admin to backup-export do you mean a project admin or something higher?
 
See my answer earlier re: needing access to NERC openstack in order to actually test out the migration steps.

> Is there a way to batch migrate the Security Groups?

I'm not aware of any existing tools for doing this. Generally, you (whereby "you" I mean "a person deploying services into a cloud environment") should be generating your security groups from some external source of data (e.g., ansible playbooks or terraform or something), so that re-creating them in a new environment is just a matter of pointing your tooling at the new environment. 

Having said that, one could probably script up a solution to perform the necessary extract-and-import.

**Comment by joachimweyl** [comment]
@larsks Let's get you access.
- [ ] [FAS RC Access](https://portal.rc.fas.harvard.edu/request/account/new/user) required sounds like you have that
- [ ] [NERC Project Request](https://regapp.mss.mghpcc.org/) - Justin/Scott approves
- [ ] [PI Request](https://docs.google.com/forms/d/e/1FAIpQLSdscMlm3TQR09sl7P-0n4oN1uzpd7YikqDubEYF2QDLVz6djA/viewform?pli=1&fbzx=-8227359805748438031) - Milson approves
- [ ] [Quaota Request](https://coldfront.mss.mghpcc.org/user/login) - Milson approves
- [ ] Confirm access to [NERC Dashboard](https://stack.nerc.mghpcc.org/dashboard)

**Comment by larsks** [comment]
(a) almost done, and (b) nope, unless you can give me a time machine.

**Comment by joachimweyl** [comment]
I'll open a new issue to create a time machine 😄

**Comment by joachimweyl** [comment]
the migration testing piece of this is being tracked here https://github.com/CCI-MOC/documentation/pull/117

**Comment by joachimweyl** [comment]
This is now live [Step1](https://nerc-project.github.io/nerc-docs/migration-moc-to-nerc/Step1/), [Step2](https://nerc-project.github.io/nerc-docs/migration-moc-to-nerc/Step2/), [Step3](https://nerc-project.github.io/nerc-docs/migration-moc-to-nerc/Step3/).
