### ISSUE TITLE
Track down Allocation for NERC OpenShift/Stack

### ISSUE THREAD

**Issue by joachimweyl** [CCI-MOC/ops-issues#898]
After further consideration, it was decided that we would focus on the Allocation data which Justin was able to pull from ColdFront.

# OpenShift
Helpful information but not needed for this round of data gathering
1. Working with @computate to get access to the [Grafana](https://grafana-open-cluster-management-observability.apps.nerc-ocp-infra.rc.fas.harvard.edu/) metrics.
   1. was added to [nerc-logs-metrics](https://github.com/orgs/OCP-on-NERC/teams/nerc-logs-metrics) team on OCP-on-NERC
   1. Working on getting this [PR](https://github.com/OCP-on-NERC/nerc-ocp-config/pull/238) merged so that this team gets access to Grafana.
   1. @computate applied resources to the infra cluster to give me access until the PR is done
1. Digging into Grafana to Gather data
   1. [CPU, Memory & Network Usage](https://grafana-open-cluster-management-observability.apps.nerc-ocp-infra.rc.fas.harvard.edu/d/8Qvi3edMz/acm-resource-optimization-cluster?var-cluster=nerc-ocp-prod&orgId=1&refresh=5m) (NERC FAS RC VPN Required)
1. Will use data Justin pulled from ColdFront

# OpenStack
Start with finding VCPU allocated to projects
1. Working with @Milstein to get access to cluster-level metrics for OpenStack.
1. Also working with @rob-baron to see if XDMoD has cluster-level metrics for OpenStack
1. Will use data Justin pulled from ColdFront

**Comment by joachimweyl** [comment]
1. Are we measuring by flavors or by max CPU, Memory, and Storage?
1. Do we have to do storage since that is not gathered by XDMoD yet?
1. Should we be bypassing XDMoD for this first round and pull directly from Coldfront?

**Comment by rob-baron** [comment]
1) We are using flavors to measure cluster wide CPU usage and memory.  

Xdmod uses "Storage Metrics" to store information regarding storage, I've created this issue for this (https://github.com/CCI-MOC/xdmod-cntr/issues/87).

What we can do is to query OpenStack concerning block and object storage, placing each type as a different resource.  It is not the most convenient way for me to think about a project (I usually think a project has multiple resources as opposed to a resource having multiple projects.

2) We do not have to storage yet as the hierarchy was a higher priority.

3) If you want to bypass xdmod, it should be storage used from openstack, openshift, and from NESE unless we want to charge based off of quota.  For storage, charging by quota makes more sense as we cannot over subscript storage.  

We should eventually pull in to xdmod information on quota and usage so that we can see about generating a utilization per project as this will be important for show back.
