### ISSUE TITLE
Research firewall appliances for ESI network expansion

### ISSUE THREAD

**Issue by hakasapl** [CCI-MOC/ops-issues#960]
Palo alto or cisco?

**Comment by msdisme** [comment]
Summary of Jun 13 slack discussion: purchase via netgate and add pfsense on top of it. 

Closing now, order in https://github.com/CCI-MOC/ops-issues/issues/995



From Jun 13 slack discussion:
er1p
 we don't do a lot of work with this, but we do have one of our large customers using Netgate appliances https://www.netgate.com/appliances

netgate.comnetgate.com
[Appliances](https://www.netgate.com/appliances)
Compare the wide range of appliances by Netgate. From desktop to rack there are products that meet all different cost, performance, and specification needs
[11:30 AM](https://massopencloud.slack.com/archives/C051SVA0PF0/p1686670239981459)
these are small Intel motherboards inside - so an "appliance" with mostly software
[11:30 AM](https://massopencloud.slack.com/archives/C051SVA0PF0/p1686670247504539)
that same software can run on more generic servers
[11:31 AM](https://massopencloud.slack.com/archives/C051SVA0PF0/p1686670269490729)
if y'all want to try this out, we can deploy one or two of those appliances for you to try the software feature/function and then we can either get you one of these appliances - they are cheap - OR pick one of the small Dell servers - R630 will work fine - to run the software on - our existing customer uses the appliances because they were cheaper than any server we could offer them at the time (edited) 
[12:01 PM](https://massopencloud.slack.com/archives/C051SVA0PF0/p1686672111284139)
Hakan Saplakoglu
:spiral_calendar_pad: Thanks! I’ll get back to you (edited) 
[12:39 PM](https://massopencloud.slack.com/archives/C051SVA0PF0/p1686674389891469)
Hakan Saplakoglu
:spiral_calendar_pad: 
[@er1p](https://massopencloud.slack.com/team/U03279BJGB1)
 the netgate appliances look good to me. Is it best to just order from their website or will your price be different? For this config: https://shop.netgate.com/products/1541-max-pfsense?variant=32156884369523
[1:29 PM](https://massopencloud.slack.com/archives/C051SVA0PF0/p1686677386188179)
er1p
 that's a newer model appliance from what we have in stock - so just as easy if you purchase it yourself
:+1:
1
