### ISSUE TITLE
R1-PA will undergo significant maintenance during the summer

### ISSUE THREAD

**Issue by hakasapl** [CCI-MOC/ops-issues#987]
NERC workers are in this pod and power might be completely shut off. There is a possibility that only one bus bar will be down at a time, but it is not clear yet. Unless the bus bar A/B swap is confirmed, we need to find a new place for the workers.

the power outage will be multiple weeks.

**Comment by hakasapl** [comment]
Both A/B busses will be down for an unknown amount of time in R1-PA. UMass has provided a rack for us to use: `R1-PC-C20`. We will need to swap the current NERC rack `R1-PA-C07` to this new rack ideally by **mid August**.

The swap will be handled by the facility, but we will need to get in touch with Nick to find out where those network uplinks go because those will need to go to the new rack instead. Downtime will be 1-2 days for every working in NERC ocp.

**Comment by amento617** [comment]
Hello Hakan,

NERC cabinet 1-A-8 is connected via 2 duplex OM3 fiber links and 2 copper
cat5a links fed from cabinet 2-A-11 (ZDA). We can move these links to
2-C-11 (ZDA) to serve 1-C-20.

However since cabinet 20 is a longer distance then cabinet 8 to row 2 ZDAs
we may need longer cabling.

Is there a date this needs to be completed by?

-n

**Comment by hakasapl** [comment]
The move is scheduled for 8/21 (Monday). The facility will swap the racks. I'll be on-site that day to help/coordinate

**Comment by hakasapl** [comment]
Done
